services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    restart: always  
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - "8081:8080"
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
